import type { NextPageContext } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ChatRoomType } from "../types/chat";
import { EnterNamePopup } from "@components/EnterName";
import Link from "next/link";

type ChatRoomCardProps = {
  children: React.ReactNode;
};

const ChatRoomCardContainer = ({ children }: ChatRoomCardProps) => {
  return <div className={styles.grid}>{children}</div>;
};

const ChatRoomCard = ({data}: {data: ChatRoomType} ) => {
  return (
    <Link href={`/wsroom/${data._id}`} className={styles.card}>
      <h2>{data.name} &rarr; </h2>
      <p>{data.description}</p>
    </Link>
  );
};

const Dashboard = ({rooms}: {rooms: ChatRoomType[]}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ChatRoomCardContainer>
          {rooms.map((v:ChatRoomType) => (
            <ChatRoomCard data={v} key={v.id}/>
          ))}
        </ChatRoomCardContainer>
      </main>

      <footer className={styles.footer}></footer>
      <EnterNamePopup/>
    </div>
  );
};

const fetchPosts = async () => {
  const response = await fetch("http://localhost:8000/api/chatroom", {
    cache: "no-store",
  });
  return response.json();
};

Dashboard.getInitialProps = async (ctx: NextPageContext) => {
    const json = await fetchPosts();
    return {rooms:json.data} 
}

export default Dashboard;
